### ISSUE TITLE
when execute #make command , a 'file format is not recognized!' error has happend!

### ISSUE THREAD

**Issue by gemfirer** [Caesar11/gStore#1]
objs/gload.o: file not  recognized: file format not recognized.
collect2:ld returned 1 exit status
make:*** [gload]  Error 1

Linux OS is CentOS 6.5 x86_64. 

Can you tell me what version is the default installed Linux?

**Comment by Caesar11** [comment]
Hi. I have tested this compile command on CentOS 6.6 x86_64 and CentOS 6.2 x86_64. The version of gcc is 4.4.7.
Did you run the “make lib_antlr” command successfully? If yes, system will output messages like this:
...
libtool: link: ranlib .libs/libantlr3c.a
libtool: link: ( cd ".libs" && rm -f "libantlr3c.la" && ln -s "../libantlr3c.la" "libantlr3c.la" )
make[2]: Leaving directory `/media/wip/hanshuo/temp/gStore/tools/libantlr3c-3.4'
make[1]: Leaving directory `/media/wip/hanshuo/temp/gStore/tools/libantlr3c-3.4'
rm -rf lib/libantlr.a
ar -crv lib/libantlr.a tools/libantlr3c-3.4/*.o 
a - tools/libantlr3c-3.4/antlr3baserecognizer.o
a - tools/libantlr3c-3.4/antlr3basetreeadaptor.o
a - tools/libantlr3c-3.4/antlr3basetree.o
a - tools/libantlr3c-3.4/antlr3bitset.o
a - tools/libantlr3c-3.4/antlr3collections.o
a - tools/libantlr3c-3.4/antlr3commontoken.o
a - tools/libantlr3c-3.4/antlr3commontreeadaptor.o
a - tools/libantlr3c-3.4/antlr3commontreenodestream.o
a - tools/libantlr3c-3.4/antlr3commontree.o
a - tools/libantlr3c-3.4/antlr3convertutf.o
a - tools/libantlr3c-3.4/antlr3cyclicdfa.o
a - tools/libantlr3c-3.4/antlr3debughandlers.o
a - tools/libantlr3c-3.4/antlr3encodings.o
a - tools/libantlr3c-3.4/antlr3exception.o
a - tools/libantlr3c-3.4/antlr3filestream.o
a - tools/libantlr3c-3.4/antlr3inputstream.o
a - tools/libantlr3c-3.4/antlr3intstream.o
a - tools/libantlr3c-3.4/antlr3lexer.o
a - tools/libantlr3c-3.4/antlr3parser.o
a - tools/libantlr3c-3.4/antlr3rewritestreams.o
a - tools/libantlr3c-3.4/antlr3string.o
a - tools/libantlr3c-3.4/antlr3tokenstream.o
a - tools/libantlr3c-3.4/antlr3treeparser.o

**Comment by gemfirer** [comment]
make lib_antlr this command running is normal.

**Comment by gemfirer** [comment]
[root@localhost gStore]# make
g++ -o gload objs/gload.o objs/Bstr.o objs/Database.o objs/KVstore.o objs/Btree.o objs/CBtreeFunc.o objs/SPARQLquery.o objs/BasicQuery.o objs/ResultSet.o objs/SigEntry.o objs/Signature.o objs/Triple.o  objs/util.o objs/VSTree.o objs/IDList.o objs/EntryBuffer.o objs/LRUCache.o objs/VNode.o objs/DBparser.o objs/SparqlParser.o objs/SparqlLexer.o  objs/Operation.o objs/Socket.o objs/Server.o objs/Client.o objs/TurtleParser.o objs/RDFParser.o lib/libantlr.a 
objs/gload.o: file not recognized: File format not recognized
collect2: ld returned 1 exit status
make: *** [gload] Error 1
[root@localhost gStore]#

**Comment by gemfirer** [comment]
after updating OS to CentOS 6.6, this problem has been disappeared!

**Comment by WenJieLiHnu** [comment]
<p>111</p>
