### ISSUE TITLE
How is gStoreD related to gStore?

### ISSUE THREAD

**Issue by 5yt45ytrfyhtryr** [Caesar11/gStore#10]
What's the relation of [gStoreD](https://github.com/bnu05pp/gStoreD) with this repository? Is one a fork of the other?

**Comment by bookug** [comment]
It is the distributed version of the gStore system, and the author is also from our team.

**Comment by 5yt45ytrfyhtryr** [comment]
So should I use gStoreD if I want a distributed version of gStore, or will it eventually be merged into gStore (this repo)?

**Comment by bookug** [comment]
You can use the repo of gStoreD directly. There is a init.conf in gStoreD, and you can choose to use single-machine mode or distributed mode.
