### ISSUE TITLE
Does gStore work with N-Quads?

### ISSUE THREAD

**Issue by 5yt45ytrfyhtryr** [Caesar11/gStore#11]
Can I load n-quads into the store, such as `subject predicate object label` or does gStore only work with triples such as `subject predicate object`?

**Comment by bookug** [comment]
gStore only support RDF data sets now. If you need to deal with n-quads, please communicate with us and we will considering adding this to our TODO list.

**Comment by 5yt45ytrfyhtryr** [comment]
What do you by "RDF data set"? A list of n-quads like `subject predicate object label` is also a valid "RDF data set".

**Comment by bookug** [comment]
The RDF format I mean is a N-Triple format, like:
<xiaoming> <like> <tea> .
other formats should be transformed to this format

**Comment by r456ythgrty6u** [comment]
So I cannot have labelled graphs within the same database? :-( This is a huge limitation, because it ignores "context" entirely. Plus, SPARQL has support for sub-graphs selection though the "SELECT GRAPH" keyword.

**Comment by r456ythgrty6u** [comment]
> The RDF format I mean is a N-Triple format, like:

can't see the example.. try enclosing it with ```

**Comment by bookug** [comment]
I have built an IRC channel named #gStore on freenode, you may want to have a try:)

**Comment by bookug** [comment]
N-quads datasets are not directly supported by gStore system now.
We may consider supporting it later, but currently you should transform other formats to N-Triple.
For N-quads, you can extract the same graph labels and build a unique database for each unique graph label.
