### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by 5yt45ytrfyhtryr** [Caesar11/gStore#12]
I would like to start a gStore server listening to HTTP request. This would be really useful because other programs could query the database using HTTP. For example people could send a SPARQL query to `example.org/sparql/query/` and get a JSON in return with the results. Right now, it only seems possible to query the server through the `gclient` via a local unix socket...

**Comment by bookug** [comment]
Yes, the server and client communicate with sockets now. However, http request is already in the TODO list of our work, which is supposed to be done in a month.
