### ISSUE TITLE
"your database can not end with .db"

### ISSUE THREAD

**Issue by r456ythgrty6u** [Caesar11/gStore#15]
The handbook shows this example:
```
[bookug@localhost gStore]$ bin/gbuild LUBM10.db ./data/LUBM_10.n3
```

but I get the following error

```
$ ./bin/gbuild LUBM10.db ./data/LUBM_10.n3
profile: init.conf
the current settings are as below: 
key : value
------------------------------------------------------------
buffer_maxium : 100
db_home : .
db_suffix : .db
debug_level : simple
gstore_mode : single
operation_logs : true
thread_maxium : 1000

gbuild...
argc: 3	DB_store:LUBM10.db	RDF_data: ./data/LUBM_10.n3	
your database can not end with .db
```

Why are you putting any restriction on the name of the database anyway? It doesn't make sense to me.

**Comment by r456ythgrty6u** [comment]
Related bug when trying to "build" from the gconsole:

```
gstore>build lubm_10 ./data/LUBM_10.n3
Import dataset to build database...
DB_store: lubm_10.db	RDF_data: ./data/LUBM_10.n3
your database can not end with .db
```

note that I even did *not* write ".db" at all, anywhere.

And this is yet another error message different from the above:

```
gstore>build lubm_10.db ./data/LUBM_10.n3
Your db name to be built should not end with ".db".
```

**Comment by bookug** [comment]
Recently we change the name restrictions, but the documents do not update in time. 
Now you do not need to set ".db" by yourself, you should do like this:
bin/gbuild lubm data/LUBM_10.n3
bin/gquery lubm data/LUBM_q0.sql

**Comment by r456ythgrty6u** [comment]
> bin/gquery lubm data/LUBM_q0.sql

does `gquery` create the database every time, or is the database created only 1 time (with gbuild)?

**Comment by bookug** [comment]
gbuild create the database only one time, and gquery just load the database to answer a query each time.
You can type `bin/gquery db_name` to enter the gquery console. (then you do not need to load a database each time when you want to query)
Another choice is to use the API, please see the folder:  `api/*`
