### ISSUE TITLE
broken link to compatible RDF formats

### ISSUE THREAD

**Issue by gocarlos** [Caesar11/gStore#27]
on this side: https://github.com/Caesar11/gStore/blob/master/docs/FAQ.md
the link to __formats__ on the FAQ.md file is broken. 

```
Why does gStore report errors that the format of some RDF datasets are not supported?

gStore does not support all RDF formats currently, please see **formats** for details.
```

**Comment by bookug** [comment]
Sorry, it seems this file is lost. Do you encounter problem with formats? You can communicate with me directly, or email to bookug@qq.com
