### ISSUE TITLE
0.6.0 版的ghttp怎么同时访问多数据库

### ISSUE THREAD

**Issue by 1000-7** [Caesar11/gStore#32]
新版改为bin/ghttp lumd启动后，如果还想启动small怎么操作

**Comment by Redbudjing** [comment]
方法一：可以以网页的形式访问127.0.0.1:9000/admin.html（IP和端口为你启动http服务的IP和端口），登录进行多用户多数据库操作，（默认root用户的用户名为"root"，密码为"123456", root用户可添加其他用户，并控制其他用户对数据库的不同访问权限)，就可以再启动small
方法二：通过程序调用gStore提供的API访问http服务，进行数据库操作，启动small，具体见API的示例及说明文档
