### ISSUE TITLE
Is gStore capable of performing inference/reasoning?

### ISSUE THREAD

**Issue by 5yt45ytrfyhtryr** [Caesar11/gStore#9]
I mean this kind of inference:

Dolphin -> isA -> Mammal
Mammal -> isA -> Animal
Cat -> isA -> Animal

"SELECT Animal" will return both Cat **and** Dolphin

**Comment by bookug** [comment]
gStore system does not deal with inference. It only considers basic RDF data sets and SPARQL queries, but the schema is designed by yourself.

**Comment by 5yt45ytrfyhtryr** [comment]
The problem however is if I import two datasets that contain this relation

    dataset1:predicate    sameAs    dataset2:predicate

then, if I SELECT dataset1:predicate, the database will only return the predicates for dataset1:predicate and **not** those of dataset2:predicate (but it should, because they are the same entity).

**Comment by bookug** [comment]
gStore does not do any semantic derivation by itself. If you want to do so, please specify the "sameAs" property in your SPARQL queries.
